name: zap-baseline

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          # GitHub Token to create issues in the repository
          token: ${{ secrets.GITHUB_TOKEN }}
          # Target URL
          target: 'http://aspnet.testsparker.com/'
          
          # The Docker file to be executed
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          
          # The title for the GitHub issue to be created
          issue_title: ZAP Scan Baseline Report
          
          # The action will file the report to the GitHub issue using the issue_title input
          allow_issue_writing: true
          # The name of the artifact that contains the ZAP reports
          artifact_name: zap_scan
      - name: create sarif file from zap results
        uses: SvanBoxel/zaproxy-to-ghas@main
      - name: upload sarif file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
