on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          # GitHub Token to create issues in the repository
          token: ${{ github.token }}
          # Target URL
          target: 'http://aspnet.testsparker.com/'
          
          # The Docker file to be executed
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          
          # The title for the GitHub issue to be created
          issue_title: ZAP Scan Baseline Report
          
          # The action will file the report to the GitHub issue using the issue_title input
          allow_issue_writing: true
          # The name of the artifact that contains the ZAP reports
          artifact_name: zap_scan
          
