name: zap-api

on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.6.0
        env:
          ZAP_AUTH_HEADER_VALUE: 'Basic YWRtaW46MTIzNDU2'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: 'http://rest.testsparker.com/files/openapi-swagger_basicauthentication.yaml'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
      - name: create sarif file from zap results
        uses: SvanBoxel/zaproxy-to-ghas@main
      - name: upload sarif file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
